version: "3.8"
volumes:
  movies_db:
  media:
  static:
  elastic_data:
services:
#================================
#      POSTGRES
#================================
  db:
    image: postgres:14-alpine
    container_name: movies_postgres
    restart: always
    volumes:
      - movies_db:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_DB=movies_database

#================================
#       WEB APPLICATION
#================================
  movies_web:
    build: .
    image: movies_web
    container_name: movies_web
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app
      - media:/app/media
      - static:/app/static

#================================
#       NGINX
#================================
  nginx:
    image: nginx:1.21.6
    container_name: movies_nginx
    restart: always
    volumes:
      - static:/app/static
      - media:/app/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/:/etc/nginx/conf.d:ro
    depends_on:
      - movies_web
    ports:
      - "80:80"

#================================
#       SWAGGER
#================================
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./app/openapi.yaml:/swagger.yaml
    environment:
      - SWAGGER_JSON=/swagger.yaml
    depends_on:
      - nginx

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - db
    volumes:
      - elastic_data:/usr/share/elasticsearch/data